services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: uv-django-todo:latest
    container_name: uv-django-todo-containner
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1 # Prevents Python from buffering output, displaying logs in real-time

    # Docker Compose development watch
    develop:
      watch:
        - action: sync
          path: . # Watches the current host directory
          target: /app # Syncs to the /app directory inside the container
          ignore:
            - .venv/
            - __pycache__/
            - Learning/
            - .git/
            - "uv.lock"
            - "pyproject.toml"

        - action: rebuild
          path: pyproject.toml

        - action: rebuild
          path: uv.lock
