services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: uv-django-todo:latest
    container_name: uv-django-todo-container
    ports:
      - "8080:8080"
    command: /app/.venv/bin/python manage.py migrate
    volumes:
      - .:/app
      - /app/.venv
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: uv-django-todo-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  db_data:
