[project]
name = "learning-python-uv-Django"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.3",
    "dotenv>=0.9.9",
    "mysqlclient>=2.2.0"
]
